//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting.DataLayar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int TypeID { get; set; }
        public int amount { get; set; }
        public System.DateTime datetime { get; set; }
        public string Description { get; set; }
    
        public virtual AccountingType AccountingType { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
